import Foundation

// Beginner-facing "HOW TO USE" examples shown in the node palette's detail card
// (NodeSpecCard). Keyed by spec id; nodes without an entry just show their description.
// Style: real node + port names, → for wiring, what you SEE as the payoff.
nonisolated enum NodeUsage {
    static let text: [String: String] = [
        "face-region": "Face Region.mask → Hide.mask → Size: only the pins on your face stay visible. Or mask → Palette.t to paint the face a hot color while the room stays cold.",
        "body-region": "Set REGION = hands, then mask → Multiply.a with Noise.out → Output.z: turbulence erupts only around your hands. REGION = background + mask → Hide hides everything but you.",
        "background": "Add the node and drag R/G/B — the void behind the pins changes instantly. No wires needed.",
        "light": "Add the node, set TYPE = point, drag X/Y and watch the shading move across the cloud. INTENSITY up for drama; wire Hand Position.x → an exposed X to carry the light in your hand.",
        "shape": "Shape.shape → Output.shape turns every pin into that form. Add Spin.rot → Output.rotation to see cubes/diamonds tumble.",
        "shape-by-depth": "Depth.depth → depth, shape → Output.shape: pins near you stay spheres, far pins become the TARGET shape. Swap NEARMORPH/FARMORPH to reverse it.",
        "shape-blend": "Noise.out → amount, shape → Output.shape: the noise field decides where spheres morph into the TARGET shape, per pin.",
        "noise": "Noise.out → Output.z makes the wall boil; out → Size.size makes pins pulse in patches. Pick a MAP and wire color → Output.color for colored noise. Watch the preview in the minimap slot.",
        "counter": "Clock.quarter → count: VALUE climbs 0→1 over WRAP beats then wraps. value → Size.base = a build that resets. On Start.fired → reset restarts it with the patch.",
        "on-start": "seconds → Value Display to watch the patch clock climb from the moment the node lands. seconds → Sine.in gives an ever-evolving wave; fired → Counter.reset zeroes things at launch.",
        "toggle": "Hand Gesture.fist → flip, out → Gate.open: one fist mutes a lane, the next un-mutes. out → Binary Display shows the current state.",
        "timer": "Clock.bar → start: elapsed ramps 0→1 over DURATION each bar — wire elapsed → Displace.amount for a swell that resets. done → the next Timer chains scenes.",
        "gate": "LFO.out → in, Toggle.out → open: the wobble only passes while the toggle is up — mute any modulation on demand.",
        "sample-hold": "LFO.out → in, Clock.quarter → trigger: smooth wobble becomes stepped jumps locked to the beat. out → Palette.shift for beat-locked color moves.",
        "step-sequencer": "Clock.eighth → step, value → Size.base: an 8-step size groove. Draw the pattern with the S1–S8 sliders; stepIndex → Palette.t cycles color per step.",
        "clock": "The patch metronome: quarter/eighth/bar fire on the global BPM. quarter → Envelope.trigger → Size.size = the classic beat pulse.",
        "envelope": "Clock.quarter → trigger, out → Size.size: each beat swells and falls (ATTACK/RELEASE shape it). Also great into Displace.amount.",
        "hand-position": "x → an exposed Palette.shift and colors follow your hand across the frame; y → Camera orbit for a head-tracked stage. SMOOTHING calms jitter.",
        "hand-gesture": "palm/fist/peace/point stay HIGH while held. fist → Toggle.flip latches states; point → Shockwave.fire throws rings on a point.",
        "person-present": "entered → Shockwave.fire greets whoever walks in with a ring; present → Gate.open only lets effects run while someone is in frame.",
        "depth": "The heart node — sensor AND cloud: position/z → Output is the spine of every patch (METRIC = real-intrinsics TDLidar cloud, FREE = intrinsic-free fan). Fan depth out too: depth → Palette.t colors by distance, depth → Shape by Depth.depth morphs by distance.",
        "pinout": "Pin-art with real 3D depth: Depth.position → position, Depth.z → z, both outs → Output. Points lock to the home grid and extend by true metric depth. MORPH 0→1 melts the grid back into the cloud — drive it with an LFO for grid↔cloud breathing.",
        "palette": "Any 0-1 field → t becomes color: Depth.depth → t = thermal camera look. SHIFT slides the map; drive t with Noise.out for animated color fields.",
        "lfo": "The free-running modulator: out → Size.size (breathing), out → an exposed Twist.angle (swaying), RATE at 8 with SQUARE = strobe.",
        "random": "A frozen per-pin random 0-1: out → Size.size gives every pin its own size; out → Palette.t confetti-colors the wall. Reseed with SEED.",
        "shockwave": "Fires expanding rings: Beat Trigger.low → fire (or tap the viewport). pulse → Output.z kicks the wall outward; pulse → Size.size makes rings of giant pins.",
        "freeze": "Wire a field through it and raise HOLD to 1: the field statues mid-motion, release melts back to live. The freeze pad drives this node.",
        "value-display": "The multimeter: wire anything → in and read the live number on the card. First stop when a patch 'does nothing' — check the signal is actually moving.",
        "binary-display": "YES/NO readout for triggers and gates: Hand Gesture.fist → in confirms the gesture actually fires before you wire it into the patch.",

        // ---- generated from the registry audit (verified port names) ----
        "abs": "Subtract.out → in; out → Size.size sizes pins by how far two fields differ, always positive.",
        "add": "Wave.height → a, Ripple.height → b; out → Output.z stacks two motions on the wall — the standard way to sum surfaces.",
        "audio-levels": "No inputs; bass → Size.size makes the cloud thump with the kick (allow mic access — the mic starts the moment the node exists). mid/high/rms too.",
        "audio-rms": "rms → Shape Morph.blend morphs spheres → cubes with overall loudness — currently identical to Audio Levels.rms.",
        "beat-trigger": "low → Envelope.trigger, Envelope.out → Strobe Color.flash: kick drums flash the cloud. mid/high catch snares and hats.",
        "bloom": "Add it and raise INTENSITY: bright pins halo. Pair with Palette's hot ends, Strobe Color flashes, or Render Settings GHOST for full hologram glow.",
        "brightness": "Video Color.color → color, out → Output.color; GAIN 2 doubles the feed, LIFT raises the black floor — quick exposure trim before Output.",
        "burst": "burst → Strobe Color.flash — sudden loud hits (claps, stabs) pop the cloud white for a few frames.",
        "camera": "No wires — the renderer reads the Camera node directly (any Camera, not just the default). Raise PARALLAX + DEPTH PUSH and jog ORBIT X/Y to turntable the cloud in 3D.",
        "chance": "Clock.quarter → trigger, PROBABILITY 0.5; out → Envelope.trigger fires the swell on a random half of the beats.",
        "clamp": "Noise.out → in, MIN 0 MAX 1; out → Output.z stops spikes punching through the camera — the seatbelt before any output.",
        "color-clamp": "Palette.color → color, out → Output.color; LOW 0.2 crushes blacks up to grey, HIGH 0.8 clips highlights flat.",
        "color-gamma": "Video Color.color → color, out → Output.color; GAMMA 0.5 lifts shadow detail, 2 sinks it into black.",
        "color-invert": "Video Color.color → color, out → Output.color for a live negative; AMOUNT 0.5 sits halfway between original and inverse.",
        "color-levels": "Video Color.color → color, out → Output.color; one node for the full tone chain — GAMMA curve first, then GAIN multiply and LIFT add.",
        "color-mix": "Palette.color → a, Video Color.color → b, Depth.depth → t, out → Output.color: far pins show the palette, near pins the camera feed.",
        "color-screen": "Palette.color → a, Video Color.color → b, out → Output.color: screen-blends the two layers — only ever brightens, like stacked projectors.",
        "comment": "Type straight on the card while it's selected (or in the NOTE field below). Park one beside a cluster to explain a patch — the Device Test template uses them as a checklist.",
        "compare": "Depth.depth → a, Constant.out (VALUE 0.5) → b; aGreater → Hide.mask shows only pins nearer than the cutoff.",
        "constant": "No inputs; out → Size.size with VALUE 2 doubles every pin, or wire it into any exposed param port as a fixed setting.",
        "contrast": "Video Color.color → color, out → Output.color; AMOUNT 2 crunches the feed away from mid-grey, 0.5 flattens it. Pivot stays at 0.5.",
        "delay-trigger": "Clock.quarter → in, out → Envelope.trigger: a second swell lands DELAY seconds after each beat — call-and-response choreography.",
        "depth-drive": "Depth.depth → Depth Drive.depth, Depth Drive.z → Output.z: near surfaces lift toward the camera. GAIN sets travel, GAMMA bends the response curve.",
        "depth-fog": "Video Color.color → color, Depth.depth → depth, color → Output.color: far pins sink into the FOGR/FOGG/FOGB color; DENSITY sets how thick the haze is.",
        "depth-gradient": "Depth.depth → t, color → Output.color: near pins take the NEARR/NEARG/NEARB color, far pins the FARR/FARG/FARB color — a hand-picked two-stop ramp.",
        "displace": "Scatter.offset → Displace.offset, Displace.out → Output.position: one AMOUNT knob (0-4) scales the whole motion — expose AMOUNT and drive it from Hand Pinch.distance.",
        "divide": "Depth.depth → a, Constant.out (VALUE 2) → b; out → Output.z halves the push. Divisors are kept away from 0 (sign preserved), so b = 0 reads as a tiny positive.",
        "duotone": "Video Color.color → color, color → Output.color: dark pins take the SHADOWR/G/B color, bright pins the LIGHTR/G/B color — instant risograph.",
        "echo": "Depth.z → Echo.in, Echo.out → Output.z: a soft ghost surface chases live motion by ~DELAY seconds; FEEDBACK regenerates the tail.",
        "fft-band": "Pick BAND (1 ≈ 40 Hz sub → 20 ≈ 8 kHz); level → Size.size follows just that slice of the music. Stack several nodes on different bands for a spectrum-split patch.",
        "field-curve": "Depth.depth → in, CURVE 2; out → Palette.t eases the gradient so colour piles up on the nearest pins.",
        "field-fold": "Depth.depth → in, PIVOT 0.5 GAIN 2; out → Size.size — mid-depth pins shrink to nothing, near and far pins grow: a centre-out V.",
        "fract": "Transport.time → in; out → Palette.t loops the colormap once per second — sawtooth wrap for any growing value.",
        "grain": "Add it, AMOUNT 0.15-0.3: animated film texture over the final frame (also on NDI/Record output). 1.0 = full VHS.",
        "hand-openness": "Wire amount → Shape Morph.blend (TARGET cube): a slow fist→palm sweeps spheres into cubes continuously. SMOOTHING 0.3 steadies Vision jitter.",
        "head-pose": "Expose SHIFT on Hue Shift and wire x → Hue Shift.shift: walking across frame sweeps the cloud's hue; SMOOTHING 0.5 steadies head jitter.",
        "hide": "Ellipse Region.mask → Hide.mask, Hide.size → Size.size: pins outside the circle vanish. MODE=cutoff snaps hard at THRESHOLD; INVERT flips inside/out.",
        "hsv-shift": "Palette.color → color, out → Output.color; SHIFT 0.17 rotates every hue a sixth of the color wheel — detune any map live.",
        "joint": "Pick JOINT (leftAnkle, rightShoulder…); x/y drive anything like Hand Position does, speed → Size.size lights you up when that joint moves. Slew after it for extra glide.",
        "lag": "Depth.z → Lag.in, Lag.out → Output.z: the surface catches up to live depth over HALFLIFE seconds — dreamy motion smear. HALFLIFE 0 = off.",
        "left-hand-gesture": "Wire palm → Counter.count: each left-palm show steps the counter; expose SHIFT on Palette and Counter.value → Palette.shift steps the colors.",
        "left-hand-pinch": "Set OUTMAX 1, expose FOCUS on Depth, wire distance → Depth.focus: a closed left pinch stills the cloud, spreading adds sensor life.",
        "light-gradient": "Video Color.color → color, color → Output.color: bright camera areas climb the MAP colormap; INTENSITY scales what counts as bright.",
        "live-update": "Wire Hand Gesture.palm/fist/peace/point → in1–in4: the card names whichever is active ('FIST'); HOLD bridges brief dropouts; out carries the active input's index.",
        "look-at": "Add it with Shape TYPE = slab or spike: every pin turns to face the X/Y/Z point. Expose X/Y and wire Hand Position — the whole cloud tracks your hand like iron filings.",
        "macro": "Select several nodes, hit GROUP in the bar: they collapse into one card (wires keep flowing, dragging moves the whole group). EXPAND or delete the card to spread them back out.",
        "material": "SHADING = unlit for flat poster color, matcap for a studio look, lit + low ROUGHNESS for glossy highlights (add a Light and drag it around). METALLIC tints the shine with the pin's own color.",
        "max": "Depth.depth → a, Ripple.height → b; out → Output.z lets ripples only ever raise the surface, never dig into it.",
        "midi-cc": "value → Size.size, then turn any knob on a USB or network (RTP) MIDI controller. Every CC number lands on this one node — last received wins.",
        "midi-note": "gate → Envelope.trigger and velocity → Size.size: hold any key to swell the cloud, hit harder for bigger pins.",
        "min": "Depth.depth → a, Wave.height → b; out → Output.z — each pin takes the lower surface, like water clipping through a body.",
        "mix": "Depth.depth → a, Noise.out → b; out → Output.z. T 0.5 sits halfway; expose T and wire LFO.out into its port to crossfade the two surfaces.",
        "multiply": "Size.out → a, LFO.out → b; out → Output.size pulses every pin with the LFO — the universal 'apply amount' node.",
        "ndi-out": "Menu NDI button adds it wired from Output.image; set STREAM=START and a 'Points' NDI source appears on the LAN for OBS/TouchDesigner; ALPHA=ON keys out the background.",
        "negate": "Sine.out → in; out → Add.b turns a sum into a subtraction — flips any field's sign. (Output.z floors at 0, so don't feed it directly.)",
        "one-minus": "Depth.depth → in; out → Palette.t flips the colormap so FAR pins take the hot end — the quick invert for any 0-1 field.",
        "orbit": "LFO.out → angle, offset → Output.position: the whole cloud swirls around the frame centre. FALLOFF fades the swirl toward the middle; slow LFO RATE = lazy galaxy.",
        "osc-in": "Send /points/mod/1 float 0-1 to the phone's port 9000 (TouchDesigner/Max/TouchOSC); value carries it live. One node per SLOT; value → any exposed param.",
        "osc-out": "Audio Levels.bass → value: the patch broadcasts /points/out/1 on :9001 — drive lighting rigs or another Points from this one.",
        "output": "The sink: Depth.position → position, Depth.z → z, Size.out → size, Palette.color → color; add Spin.rot → rotation and Shape.shape → shape for spinning cubes.",
        "pin-color": "Wire color → Output.color for a flat soft-grey cloud; it just passes its color input through (no color params), so put Tint or Hue Shift after it to actually color the pins.",
        "pinch-amount": "Set OUTMAX 1, expose SEPARATION on Depth, wire distance → Depth.separation: pinch closed gathers the cloud, spread fans it out.",
        "posterize": "Video Color.color → in, out → Output.color; LEVELS 4 crushes the feed into hard print-poster bands.",
        "power": "Depth.depth → in, EXPONENT 2; out → Palette.t squeezes the hot colours onto only the nearest pins.",
        "quantize": "Depth.depth → in, STEPS 6; out → Output.z terraces the cloud into flat depth shelves.",
        "radial-ripple": "Raise AMP, then Ripple.height → Output.z: rings pulse from CENTERX/CENTERY. Expose those and wire Hand Position.x/y — the ripple follows your hand.",
        "receive": "Set CHANNEL to match a Send: out carries that Send's field with no wire across the canvas. Empty or looping channels read 0.",
        "record": "Menu Record button adds it wired from Output.image; RECORD=START captures at RESOLUTION/FPS, STOP saves the take to Photos; ALPHA=ON writes transparent HEVC.",
        "remap": "Depth.depth → in, OUTMIN 0.4 OUTMAX 2; out → Size.size — near pins swell, far pins shrink. The go-to range fixer (no clamping: inputs outside INMIN/INMAX extrapolate).",
        "render-settings": "Set BLEND = ghost: pins add up as light with no depth test — the classic point-cloud hologram. Add Bloom on top; SOLID returns to opaque spheres.",
        "reroute": "Splice into a long run: Depth.depth → in, out → Depth.depth — identical values, tidier canvas.",
        "right-hand-gesture": "Wire peace → Timer.start: a right-hand peace sign launches a DURATION ramp; Timer.elapsed → Strobe Color.flash whitens the cloud as it runs.",
        "right-hand-pinch": "Set OUTMAX 1, expose AMOUNT on Displace, wire distance → Displace.amount: right-hand spread scales whatever motion field Displace is carrying.",
        "rotation": "Set X/Y/Z in turns; Rotation.rot → Output.rotation tilts every cap. Use Shape TYPE=cube or slab first — a rotated sphere looks identical.",
        "scatter": "Depth.z → Scatter.amount, Scatter.offset → Output.position: near pins explode along seeded directions (Kick Shatter template). AMOUNT 0 = every pin home; SEED re-rolls.",
        "send": "Feed any field → in and pick CHANNEL A-D: every Receive on that channel outputs it — the tidy way to route one depth chain to many far-away nodes.",
        "shape-morph": "Hand Openness.amount → Shape Morph.blend, Shape Morph.shape → Output.shape: opening your palm melts spheres into the TARGET shape (cube, cone, spike…).",
        "sine": "Grid Info.centerDist → in, FREQUENCY 20; out → Output.z draws concentric rings from the frame centre (output already 0-1 normalized).",
        "size": "LFO.out → Size.size, Size.out → Output.size: pins pulse with the LFO (SHAPE=square = strobe). BASE scales the result, MIN/MAX clamp it; size 0 hides a pin.",
        "size-by-depth": "Depth.depth → Size by Depth.depth, Size by Depth.size → Output.size: near pins swell to NEARSIZE, far pins shrink to FARSIZE — instant depth pop.",
        "slew": "Audio Levels.rms → in; out → Size.size de-zippers the jumpy level — UP and DOWN set rise/fall time in seconds.",
        "smoothstep": "Depth.depth → in, EDGE0 0.2 EDGE1 0.8; out → Hide.mask for a soft near/far reveal (then Hide.size → Size.size).",
        "spin": "Spin.rot → Output.rotation with Shape TYPE=cube: caps spin at Z turns/sec continuously off the clock — no LFO needed.",
        "spring": "Depth.z → Spring.target, Spring.out → Output.z: the surface overshoots and wobbles behind live depth. STIFFNESS 0 = off (direct follow); DAMPING tames the bounce.",
        "sqrt": "Depth.depth → in; out → Size.size fattens faint far detail while near pins barely change — a gentle ease (negatives clamp to 0).",
        "stem": "Turn ARMS on in the Depth node first, then: PROFILE blade + TAPER 0.6 = grass; round + THICKNESS up = columns.",
        "stretch": "Set Y=3; Stretch.scale → Output.stretch: every cap becomes a needle. Pair Shape TYPE=tube and Spin.rot → Output.rotation for tumbling rods.",
        "strobe-color": "Palette.color → color, Clock.quarter → Envelope.trigger, Envelope.out → flash, out → Output.color: the cloud flashes white on every beat.",
        "subtract": "Depth.depth → a, Noise.out → b; out → Output.z carves noisy dents out of the depth surface.",
        "switch": "Two fields → a and b, Toggle.out → pick; out → Output.z hard-jumps between two looks each time the toggle flips.",
        "threshold": "Depth.depth → in, LEVEL 0.5; out → Shape Morph.blend snaps close pins to cubes while far pins stay spheres — a hard 0/1 cut.",
        "threshold-color": "Video Color.color → color, color → Output.color: pins under LEVEL brightness turn the DARKR/G/B color, above turn LITER/G/B — hard two-tone poster cut.",
        "tint": "Video Color.color → color, out → Output.color; drop G and B to 0 to wash the camera feed red. R / G / B are 0-2 per-channel gains.",
        "touch": "In camera view drag the viewport: x → Twist.angle steers a whirlpool; pressed → Gate.open passes a signal only while your finger is down. Inactive while the node editor is open.",
        "trail": "Depth.z → Trail.in, Trail.out → Output.z: pins hold their peak push and sink back over DECAY seconds — comet afterimages (the Comet Trails template).",
        "transport": "Wire time → Sine.in for an endless smooth wave; beat → Palette.t sweeps the colormap once per beat at the global BPM.",
        "twist": "LFO.out → Twist.angle, Twist.offset → Output.position: the wall whirlpools around the view centre. ANGLE in turns; higher FALLOFF confines the swirl to the middle.",
        "velocity": "Depth.z → Velocity.in, Velocity.speed → Palette.t, Palette.color → Output.color: moving surfaces ignite through the map, still areas stay cold. GAIN = sensitivity.",
        "velocity-color": "Depth.z → Velocity.in, Velocity.speed → speed, color → Output.color: moving pins flare through the FIRE map, still pins sit at its dark end.",
        "vignette": "Add it: corners darken, eye goes to the centre. AMOUNT sets the falloff.",
        "wander": "No inputs; out → an exposed param port (e.g. Hue Shift SHIFT) for slow organic drift — SPEED sets kick rate, RANGE limits the span.",
        "wave": "Wave.height → Output.z: a sine sheet travels across the wall (AXIS x/y/diagonal, SPEED sets the travel). Add it to Depth.z with an Add node for rolling hills over the live surface.",
        "accumulate": "Wire it anywhere in the depth wire: ~FRAMES frames average into a denser, calmer cloud. High FRAMES = statue-smooth but laggy on motion.",
        "apple-depth-filter": "Drop it anywhere on the depth wire (Depth.depth → depth, out → Depth.depth): its presence turns on Apple's front-camera depth smoothing — steadier depth, softer silhouettes.",
        "clip-transport": "Import a video (its depth gets baked), then Video Source.depth → Depth.depth: the clip loops as a moving point cloud. NEAR/FAR/INVERT remap exactly like the Depth node.",
        "confidence": "Reads a constant 1.0 until the sensor confidence texture is bound — nothing useful to wire yet (backlog).",
        "depth-bands": "Depth.depth → Depth Bands.depth, stepped → Depth Drive.depth, z → Output.z: the push terraces into BANDS flat layers; or stepped → Palette.t for hard topo-map colour bands.",
        "depth-invert": "Depth.depth → Depth Invert.depth, out → Depth Drive.depth, z → Output.z: the push turns inside-out — the background bulges toward you. Reusable mid-chain, unlike Depth's INVERT toggle.",
        "depth-rings": "Depth.depth → Depth Rings.depth, then rings → Size.size pulses pin size along depth contours — FREQUENCY packs more rings, SHARPNESS thins them. Also nice → Palette.t.",
        "depth-slice": "Depth.depth → Depth Slice.depth, then mask → Size.size shows only pins between NEAR and FAR (0-1 nearness) — a floating slab of the scene; FEATHER softens the cut edges.",
        "despeckle-voxel": "Wire it after Depth: floating dust around silhouettes vanishes — a point needs neighbours within SIZE metres to survive.",
        "detail-upsample": "Wire it after the cleanup chain: depth resamples at FACTOR× resolution with edges snapped to the camera image — silhouettes sharpen. Costs GPU time; check FPS.",
        "domain": "Set TOPOLOGYB = spiral and drag MORPH: the grid reflows into a sunflower. Wire Hand Openness.amount → morph to open the lattice with your palm.",
        "edge-policy": "Add it with big Scatter/Twist amounts: MODE fade melts flying pins away at the border; clamp piles them into a frame; none lets them escape.",
        "ema-smooth": "Depth.depth → EMA Smooth.depth, out → Depth.depth. AMOUNT 0 = raw shimmer, 1 = statue-still statics while motion stays snappy — the everyday anti-jitter node.",
        "fill-holes": "Add it on the depth wire (Depth.depth → depth, out → Depth.depth): sensor dropouts hold their last good depth, so the cloud stops flickering in IR shadows.",
        "grazing-cull": "Insert on the depth wire: Depth.depth → Grazing Cull.depth, out → Depth.depth. Raise CULL to strip walls/floors seen edge-on; culled pins simply disappear.",
        "grid-info": "Grid Info.centerDist → Palette.t → Output.color colours rings outward from the centre; Grid Info.hash → Size.size gives every pin a stable random size.",
        "jitter": "Jitter.offset → Output.position roughs up the machine-perfect grid; AMOUNT sets the spread, SEED reshuffles. Wire Depth.depth → Jitter.amount to shake only near pins.",
        "live-depth": "No back LiDAR? Live Depth Model.depth → Depth.depth runs the camera through a monocular depth MODEL (pick MODEL + LENS in its bar); tune NEAR/FAR like Depth.",
        "proximity": "nearness → Size.base: pins swell as someone approaches (NEAR/FAR set the range). entered → Shockwave.fire greets them with a ring at THRESHOLD.",
        "region-ellipse": "Ellipse Region.mask → Hide.mask, then Hide.size → Output.size keeps pins only inside a centre circle; RADIUS/FEATHER soften the rim, INVERT punches a hole instead.",
        "region-rect": "Rect Region.mask → Multiply.a, Size.out → Multiply.b, Multiply.out → Output.size: pins outside the WIDTH×HEIGHT box vanish; FEATHER softens the cut, INVERT flips it.",
        "smooth-surface": "Wire it after Depth: surfaces flatten to glass while silhouettes stay crisp (bilateral). RADIUS 2-3 for heavy smoothing.",
        "source": "Skip it — it does nothing today. The input auto-switches by what feeds Depth.depth: Depth = live sensor, Still Image / Video Source = import, Live Depth Model = camera + ML.",
        "still-image": "Import a photo, then Still Image.depth → Depth.depth freezes it as a 3D relief; sweep NEAR/FAR to carve which depths pop forward.",
        "uv-transform": "Add it and drag SCALE: the camera image zooms under the pins while the cloud stays put. Expose OFFSETX + wire an LFO for a slow pan.",
        "video-color": "Video Color.color → Output.color paints each pin its live camera pixel; EXPOSURE lifts/darkens in stops. Pairs with Depth for a true RGB point cloud.",
    ]
}
